spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.xej.pojo
  configuration:
    map-underscore-to-camel-case: true


#shiro:
#  login-url: /welcome
#  unauthorized-url: /unauthorized
#  anon-urls:
#    - /user/toLogin